version: '3'

services:
  app: # serviço do app
    build: .
    entrypoint: .docker/entrypoint.sh
    container_name: kpopstats-app
    ports:
      - '3000:3000'
      - '5555:5555' # Usada para o Prisma Studio
    volumes:
      - .:/home/node/app
    depends_on:
      - db
  db: # serviço do bando de dados
    build: .docker/postgres
    container_name: kpopstats-db
    restart: always
    tty: true
    ports:
      - '5433:5432'
    volumes:
      - .docker/dbdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=docker #senha
      - POSTGRES_DB=kpopstats_api # nome
